Pagination
Urbork/movies-browser pull request #3
Opened 2024-04-06 08:23 UTC by mariuszmmm

Added pagination allows for:
- navigating to the first page,
- navigating to the previous page,
- navigating to the next page,
- navigating to the last page,
- displaying the current page number,
- displaying the total number of pages.
Logic for fetching data has been added to the pagination using "useState" temporarily, and it will be replaced with "Redux" store logic in the future.

2024-04-06 11:27 UTC, Urbork approved these changes
Works nice, very clean code

2024-04-06 19:10 UTC, Adrode commented
Great job, nice use of hook

2024-04-06 19:26 UTC, Adrode approved these changes
Great job! Nice use of hook, everything looks simple (in a good sense) and fine

2024-04-06 19:51 UTC, Adrode requested changes
Please, change the colors formats from RGB to HEX. Use https://chir.ag/projects/name-that-color/  to apply names of the color to theme.js and then change color names in Pagination/styled.js

2024-04-07 00:46 UTC, mariuszmmm commented
Color formats changed from RGB to HEX and added pagination function.

2024-04-07 10:34 UTC, Adrode commented on src/theme.js
> +    mobileMax: "767px",
Good job!

2024-04-07 10:34 UTC, Adrode approved these changes
Now it looks perfect!

2024-04-07 10:56 UTC, merged